# site properties and page defaults
title: 朱旺升实验室
subtitle: 植物免疫与作物抗病研究
description: 朱旺升实验室主要研究植物免疫、作物抗病以及植物与病原微生物互作的分子机制，重点解析玉米抗病遗传基础和植物免疫信号调控机制。
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: 
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: Junbin6
  twitter: 
  youtube: 

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff

# configure jekyll spaceship
jekyll-spaceship:
  mathjax-processor:
    src:
      - https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js
